### ISSUE TITLE
Adding `favicon`

### ISSUE THREAD

**Issue by tusharnankani** [philippetedajo/The-Developer-Portofolio#7]
Hi @philippetedajo!

Came across your portfolio! Neat and Brilliantly done! 🤗
Adding a favicon, would be a cherry on the top! ^_^

All the best!
Tushar Nankani

**Comment by philippetedajo** [comment]
Thanks for feedback, I apreciate, i will add a favicon soon

Le lun. 17 août 2020 à 13:19, Tushar Nankani <notifications@github.com> a
écrit :

**Comment by philippetedajo** [comment]
@tusharnankani feel free to make pull request

**Comment by tusharnankani** [comment]
Salut @philippetedajo!

The deployment I looked at a few hours ago when I opened this issue is different. I like this one a lot. The User Interface is very appealing and the animations are great! 

Great work! ^_^

**Comment by philippetedajo** [comment]
Le lun. 17 août 2020 à 19:33, Tushar Nankani <notifications@github.com> a
écrit :
